### ISSUE TITLE
gtoolkit in cloud has translucent search window

### ISSUE THREAD

**Issue by markfirmware** [markfirmware/gtoolkit-cloud#1]
(There is some discussion in the gtoolkit discord help channel regarding skia, glutin, and whether a cloud node has the requisite gpu resources. This problem may also occur on desktop virtual environments.)

See [readme for reproduction](https://github.com/markfirmware/gtoolkit-cloud/#readme)

Press search button and you get a translucent window:

![Screenshot from 2021-02-04 15-36-40](https://user-images.githubusercontent.com/22677068/106952253-dec34e80-66fe-11eb-95c7-01d6a4453a55.png)

When started:

    [Glutin] Profile #0 worked
    [Warning] Failed to release GlutinContextBuilder(@ 16r55E550DE3F70) due to PrimitiveFailed: primitive #loadSymbol:module: in ExternalAddress class failed
    [Warning] Failed to release GlutinContextBuilder(@ 16r00000000) due to PrimitiveFailed: primitive #primitiveReleaseParameters:releaseReturn: in TFPooledExternalAsyncCall failed
    [Warning] Failed to release GlutinContextBuilder(@ 16r55E551198390) due to PrimitiveFailed: primitive #loadSymbol:module: in ExternalAddress class failed
    [Warning] Failed to release GlutinContextBuilder(@ 16r00000000) due to PrimitiveFailed: primitive #primitiveReleaseParameters:releaseReturn: in TFPooledExternalAsyncCall failed
    [Warning] Failed to release GlutinContextBuilder(@ 16r55E551132020) due to PrimitiveFailed: primitive #loadSymbol:module: in ExternalAddress class failed
    [Warning] Failed to release GlutinContextBuilder(@ 16r00000000) due to PrimitiveFailed: primitive #primitiveReleaseParameters:releaseReturn: in TFPooledExternalAsyncCall failed
    [Warning] Failed to release GlutinContextBuilder(@ 16r55E55174A880) due to PrimitiveFailed: primitive #loadSymbol:module: in ExternalAddress class failed
    [Warning] Failed to release GlutinContextBuilder(@ 16r00000000) due to PrimitiveFailed: primitive #primitiveReleaseParameters:releaseReturn: in TFPooledExternalAsyncCall failed
    [Glutin] Profile #0 worked

As seen here in the gitpod browser tab:
![Screenshot from 2021-02-04 15-45-44](https://user-images.githubusercontent.com/22677068/106953196-167ec600-6700-11eb-8f9a-78230e5b7fec.png)

**Comment by markfirmware** [comment]
@csweichel of gitpod - does gitpod offer information on what graphics capabilities are provided by its nodes, and guidance for finding more capabilities?

cc @syrel of gtoolkit

**Comment by markfirmware** [comment]
Now only reporting

    [Glutin] Profile #0 worked
    [Glutin] Profile #0 worked

without the error messages. No known reason for this change in reporting.

@syrel @girba

**Comment by khinsen** [comment]
I see the same problem when running GT under Ubuntu 20.04 running in a virtual machine (VirtualBox) under macOS:
![Screenshot 2021-03-16 at 11 31 53](https://user-images.githubusercontent.com/94934/111295142-5748f380-864b-11eb-9760-c37a270e4806.png)

**Comment by markfirmware** [comment]
This no longer occurs on gitpod nor on a debian 11 droplet.
